# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

page:
  show_prev_next: false


# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Teja Teppala'
    description: 'Astrophysicist, science communicator, and policy advocate studying galaxy formation and evolution.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''
    
# Site icon (favicon and app icons)
icon:
  favicon: favicon.png
  apple_touch_icon: apple-touch-icon.png

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Teja Teppala"

# Site footer
footer:
  copyright:
    notice: '© {year} Teja Teppala. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
