# Setup
title:        Teja Teppala
tagline:      Doctoral Candidate in Astronomy | Researcher | STEM Communicator
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Teja Teppala
  url:        https://tejateppala.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
